env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: linux
    ldflags:
      - -s -w -extldflags "-static"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  name_template: "{{ .ProjectName }}-linux-checksums.txt"
