env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: darwin
    ldflags:
      - -s -w -extldflags "-static"
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  name_template: "{{ .ProjectName }}-mac-checksums.txt"