env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: windows
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static"
    goos:
      - windows
    goarch:
      - amd64

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  name_template: "{{ .ProjectName }}-windows-checksums.txt"