#  https://github.com/projectdiscovery/naabu
name: 🎉 Release Binary

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: Install Dependences
        run: brew install libpcap
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release -f .github/goreleaser/mac.yml --rm-dist
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.APPPUB }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: Install Dependences
        run: sudo apt install libpcap-dev

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release -f .github/goreleaser/linux.yml --rm-dist
          workdir: .
        env:
          GITHUB_TOKEN: "${{ secrets.APPPUB }}"

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release -f .github/goreleaser/windows.yml --rm-dist
          workdir: .
        env:
          GITHUB_TOKEN: ${{ secrets.APPPUB }}